$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

display_name: intrusion_detection_phase2_training
experiment_name: intrusion_detection_phase2_experiment

code: ..

command: >
  python src/train.py
  --data ${{inputs.curated_data}}
  --output ${{outputs.model_output}}

inputs:
  curated_data:
    type: uri_file
    path: ../data/curated/selected_features.csv

outputs:
  model_output:
    type: uri_folder

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: ../env/conda.yml

compute: azureml:computeclusterproject
